### PR TITLE
cocoa: change Shape data to use ObjC objects instead of C structs.

### LINKED ISSUE #6089: SDL 2.24.0 fails to build on macOS < 10.14
The failing compile command and error are:
```
libtool: compile:  /usr/bin/clang -pipe -Os -arch x86_64 -I/opt/local/include -DUSING_GENERATED_CONFIG_H -Iinclude -I/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_libsdl2/libsdl2/work/SDL2-2.24.0/include -idirafter /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_libsdl2/libsdl2/work/SDL2-2.24.0/src/video/khronos -DSDL_BUILD_MAJOR_VERSION=2 -DSDL_BUILD_MINOR_VERSION=24 -DSDL_BUILD_MICRO_VERSION=0 -mmmx -m3dnow -msse -msse2 -msse3 -Wall -fno-strict-aliasing -DTARGET_API_MAC_CARBON -DTARGET_API_MAC_OSX -fobjc-arc -fvisibility=hidden -Wdeclaration-after-statement -Werror=declaration-after-statement -DMESA_EGL_NO_X11_HEADERS -DEGL_NO_X11 -D_THREAD_SAFE -MMD -MT build/SDL_cocoashape.lo -c /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_libsdl2/libsdl2/work/SDL2-2.24.0/src/video/cocoa/SDL_cocoashape.m  -fno-common -DPIC -o build/.libs/SDL_cocoashape.o

In file included from /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_libsdl2/libsdl2/work/SDL2-2.24.0/src/video/cocoa/SDL_cocoashape.m:27:
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_libsdl2/libsdl2/work/SDL2-2.24.0/src/video/cocoa/SDL_cocoashape.h:33:24: error: ARC forbids Objective-C objects in struct
    NSGraphicsContext* context;
                       ^
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_libsdl2/libsdl2/work/SDL2-2.24.0/src/video/cocoa/SDL_cocoashape.m:61:13: error: ARC forbids Objective-C objects in struct
    NSView* view;
            ^
```

Full build output for 10.13 is available here: https://build.macports.org/builders/ports-10.13_x86_64-builder/builds/160213/steps/install-port/logs/stdio

### PR DESCRIPTION
**Pull request by slime73**
## Description
Objective-C with ARC works best when Objective-C objects have direct references in other ObjC objects instead of in C structs. In #5632 I changed most of the Cocoa backend code to use this convention but missed the shaped window code. Apparently this caused compilation problems on some systems, but not on mine.

## Existing Issue(s)
Fixes #6089
I also think I discovered #6104 while making this change.

### CODE REVIEW

**Comment by sezero** [comment]
Is this eligible for 2.24.x branch?

**Comment by slouken** [comment]
> Is this eligible for 2.24.x branch?

Yep!

**Comment by slime73** [comment]
I'm still confused as to why it works/worked for some people and not others, without the patch.
