### ISSUE TITLE
error: declaration for parameter

### ISSUE THREAD

**Issue by shoober420** [libsdl-org/SDL#4780]
Im getting spammed by `error: declaration for parameter` errors when compiling libsdl2 from commit https://github.com/libsdl-org/SDL/commit/7becc414951a15043417c43f0e5efb0f60c5178d on Gentoo Linux using GCC 12.0.0 20210925 https://github.com/gcc-mirror/gcc/commit/9a4293ed9bdd029dd44d19b412b1cdf12372801e. Here is a snippet of the error with the full log attached (its big).

[buildlibsdl2.log](https://github.com/libsdl-org/SDL/files/7230271/buildlibsdl2.log)

```
/var/tmp/portage/media-libs/libsdl2-9999/work/libsdl2-9999-abi_x86_32.x86/src/events/../dynapi/SDL_dynapi_overrides.h:453:25: error: declaration for parameter 'SDL_SetColorKey_REAL' but no such parameter
  453 | #define SDL_SetColorKey SDL_SetColorKey_REAL
      |                         ^~~~~~~~~~~~~~~~~~~~
include/SDL_surface.h:439:29: note: in expansion of macro 'SDL_SetColorKey'
  439 | extern DECLSPEC int SDLCALL SDL_SetColorKey(SDL_Surface * surface,
      |                             ^~~~~~~~~~~~~~~
/var/tmp/portage/media-libs/libsdl2-9999/work/libsdl2-9999-abi_x86_32.x86/src/events/../dynapi/SDL_dynapi_overrides.h:770:27: error: declaration for parameter 'SDL_HasSurfaceRLE_REAL' but no such parameter
  770 | #define SDL_HasSurfaceRLE SDL_HasSurfaceRLE_REAL
      |                           ^~~~~~~~~~~~~~~~~~~~~~
include/SDL_surface.h:415:34: note: in expansion of macro 'SDL_HasSurfaceRLE'
  415 | extern DECLSPEC SDL_bool SDLCALL SDL_HasSurfaceRLE(SDL_Surface * surface);
      |                                  ^~~~~~~~~~~~~~~~~
/var/tmp/portage/media-libs/libsdl2-9999/work/libsdl2-9999-abi_x86_32.x86/src/events/../dynapi/SDL_dynapi_overrides.h:452:27: error: declaration for parameter 'SDL_SetSurfaceRLE_REAL' but no such parameter
  452 | #define SDL_SetSurfaceRLE SDL_SetSurfaceRLE_REAL
      |                           ^~~~~~~~~~~~~~~~~~~~~~
include/SDL_surface.h:402:29: note: in expansion of macro 'SDL_SetSurfaceRLE'
  402 | extern DECLSPEC int SDLCALL SDL_SetSurfaceRLE(SDL_Surface * surface,
      |                             ^~~~~~~~~~~~~~~~~
/var/tmp/portage/media-libs/libsdl2-9999/work/libsdl2-9999-abi_x86_32.x86/src/events/../dynapi/SDL_dynapi_overrides.h:451:24: error: declaration for parameter 'SDL_SaveBMP_RW_REAL' but no such parameter
  451 | #define SDL_SaveBMP_RW SDL_SaveBMP_RW_REAL
      |                        ^~~~~~~~~~~~~~~~~~~
include/SDL_surface.h:376:29: note: in expansion of macro 'SDL_SaveBMP_RW'
  376 | extern DECLSPEC int SDLCALL SDL_SaveBMP_RW
      |                             ^~~~~~~~~~~~~~
/var/tmp/portage/media-libs/libsdl2-9999/work/libsdl2-9999-abi_x86_32.x86/src/events/SDL_events.c:1230: error: expected '{' at end of input
make: *** [Makefile:323: build/SDL_events.lo] Error 1
```

**Comment by vivazkote** [comment]
same

**Comment by viliml** [comment]
It's because code samples from the wiki are automatically pasted into block comments in the headers. When the code sample itself contains a block comment, the end of the block comment in the same will end the whole block comment in the header and cause a million syntax errors when the remainder of the comment gets treated like code.

**Comment by icculus** [comment]
Shoot, the code block shouldn't be merged to the headers. I'll fix that.

**Comment by icculus** [comment]
This is resolved by https://github.com/libsdl-org/sdlwiki/commit/9edce5c84aa017f87c0d9a7f3fb6941716c30105, which generated this commit to SDL: https://github.com/libsdl-org/SDL/commit/7a1690eb633608b325301ab54f04970a46a2d6aa

**Comment by nanfengnan1** [comment]
OK, @icculus , can you tell me how to resolve this problem. i meet many the samiliar qz. look forward you answer.

**Comment by icculus** [comment]
@nanfengnan1 Is this not working with the 2.30.0 release? We fixed this in 2021.

**Comment by nanfengnan1** [comment]
no，i use frr master code and i find 8.5 version has no this error.



---Original---
From: "Ryan C. ***@***.***&gt;
Date: Tue, Mar 5, 2024 12:57 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [libsdl-org/SDL] error: declaration for parameter (#4780)




 
@nanfengnan1 Is this not working with the 2.30.0 release? We fixed this in 2021.

**Comment by nanfengnan1** [comment]
okay, i will search commit log.

**Comment by nanfengnan1** [comment]
@viliml , i don't konw why generate this problem?
