### ISSUE TITLE
Fixed build with mesa 19.2.1

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3440]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [Patch to fix build issue (0002-Fixed-build-with-mesa-19.2.1.patch, text/plain, 2019-10-24 20:46:24 +0000, 1943 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=4018)

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Linux, x86

# Comments on the original bug report:

On 2019-10-24 20:46:24 +0000, Alistair wrote:

> Created attachment 4018
> Patch to fix build issue
> 
> Fix the following two build failures when building for x86 with mesa 19.2.1
> 
> In file included from /include/SDL_opengles.h:33,
>                  from /src/video/SDL_video.c:41:
> /usr/include/GLES/gl.h:63:25: error: conflicting types for 'GLsizeiptr'
>   63 | typedef khronos_ssize_t GLsizeiptr;
>      |                         ^~~~~~~~~~
> In file included from /include/SDL_opengl.h:2105,
>                 from /src/video/SDL_video.c:37:
> /include/SDL_opengl_glext.h:472:19: note: previous declaration of 'GLsizeiptr' was here
>  472 | typedef ptrdiff_t GLsizeiptr;
>      |                   ^~~~~~~~~~
> 
> 
> In file included from /include/SDL_opengles.h:33,
>                 from /src/video/SDL_video.c:41:
> /usr/include/GLES/gl.h:64:26: error: conflicting types for 'GLintptr'
>   64 | typedef khronos_intptr_t GLintptr;
>      |                          ^~~~~~~~
> In file included from /include/SDL_opengl.h:2105,
>                 from /src/video/SDL_video.c:37:
> /include/SDL_opengl_glext.h:473:19: note: previous declaration of 'GLintptr' was here
>  473 | typedef ptrdiff_t GLintptr;
>      |                   ^~~~~~~~

On 2019-10-25 13:35:10 +0000, Sylvain wrote:

> Isn't this fixed by this one ?
> 
> Fixed bug 4797 - SDL fails to compile with Mesa Master (thanks Michael Olbrich!)
> https://hg.libsdl.org/SDL/rev/369b01006eb2

On 2019-10-25 21:54:51 +0000, Alistair wrote:

> Ah yes it is. This build failure is for the release, not the latest. This is no longer an issue.

On 2019-10-25 21:55:30 +0000, Alistair wrote:

> Already fixed
