### ISSUE TITLE
joystick/iphoneos/SDL_mfijoystick.m fails to compile on macOS 10.11.6: unexpected @ in program

### ISSUE THREAD

**Issue by nbriggs** [libsdl-org/SDL#4992]
On macOS 10.11.6, with current SDL (commit c97b721868b2f005d7f2b1cbd502a6d6ad5fdd85) doing
```
./configure && make
```
results in
```
  CC     build/SDL_mfijoystick.lo
/Users/briggs/Projects/SDL/src/joystick/iphoneos/SDL_mfijoystick.m:1341:13: error: unexpected '@' in program
        if (@available(macos 11.0, iOS 14.0, tvOS 14.0, *)) {
            ^
```
Workaround:  ./configure --disable-joystick

config.log and config.status (renamed to config.status.txt) attached
[config.log](https://github.com/libsdl-org/SDL/files/7577709/config.log)
[config.status.txt](https://github.com/libsdl-org/SDL/files/7577713/config.status.txt)
.

**Comment by sezero** [comment]
Does the patch at https://github.com/libsdl-org/SDL/issues/4958#issuecomment-974887824 help instead?

**Comment by nbriggs** [comment]
I'll check, give me a moment though.

**Comment by nbriggs** [comment]
@sezero -- Yeah, no compilation error after applying just the one patch to src/joystick/iphoneos/SDL_mfijoystick.m from #4958 (and reconfiguring to reenable the joystick code)
```
SDL2 Configure Summary:
Building Shared Libraries
Building Static Libraries
Enabled modules : atomic audio video render events joystick haptic hidapi sensor power filesystem threads timers file loadso cpuinfo assembly
Assembly Math   : mmx 3dnow sse sse2 sse3
Audio drivers   : disk dummy coreaudio
Video drivers   : dummy cocoa metal x11(dynamic) opengl opengl_es2 opengl vulkan
X11 libraries   : xcursor xdbe xinerama xinput2 xinput2_multitouch xfixes xrandr xscrnsaver xshape xvidmode
Input drivers   :
Enable virtual joystick APIs : YES
```

**Comment by sezero** [comment]
OK, patch applied as https://github.com/libsdl-org/SDL/commit/ee2afa00ba2b0c6bb52eae66259e0b6a01098a77

**Comment by nbriggs** [comment]
Thanks.  I've updated and verified it's good as released.
