### ISSUE TITLE
configure bug __has_feature macro not detected

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1612]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Mac OS X 10.6, x86

# Comments on the original bug report:

On 2014-08-20 03:32:14 +0000, skaller wrote:

> using gcc 4.2 (the default) on Mac OSX 10.6.8
> 
>  CC     build/SDL_dynapi.lo
> In file included from /Users/johnskaller/SDL/src/dynapi/SDL_dynapi.c:31:
> include/SDL_syswm.h:211:39: error: missing binary operator before token "("
> 
> The fault appears to be here:
> 
> #if defined(__OBJC__) && __has_feature(objc_arc)
> 
> that the __has_feature macro is not supported by gcc 4.2.
> 
> The code works fine with my clang 3.3svn. 
> 
> Gcc cannot be upgraded on OSX. Therefore:
> 
> Either the configure script should check for clang on OSX
> and use that as the default, or this macro must be configured
> out (since it can't be supported by any gcc on OSX).

On 2014-08-20 04:17:56 +0000, Sam Lantinga wrote:

> Can you check to see if this fixes it?
> https://hg.libsdl.org/SDL/rev/65a23b7b43c7
> 
> Thanks!

On 2014-08-20 05:01:08 +0000, Alex Szpakowski wrote:

> I think a more robust way would be to check whether '__has_feature' is defined, rather than just checking which compiler was used.

On 2014-08-20 05:04:03 +0000, Sam Lantinga wrote:

> Is it a simple macro? I agree that would be a better fix if we can simply do && defined(__has_feature)

On 2014-08-20 05:05:37 +0000, Sam Lantinga wrote:

> Yeah, that totally works, thanks! :)
> https://hg.libsdl.org/SDL/rev/5bbfdfa38bfc

On 2014-08-20 05:06:40 +0000, Alex Szpakowski wrote:

> Yeah, it's listed as a macro here http://clang.llvm.org/docs/LanguageExtensions.html#feature-checking-macros , and Xcode sees it as a macro too.
