### PR TITLE
Check also for __ARM_ARCH in SDL_atomic.h

### PR DESCRIPTION
**Pull request by pkubaj**
## Description

Otherwise building openrct2 on FreeBSD/armv7 fails with:
`In file included from /usr/ports/games/openrct2/work/OpenRCT2-0.4.1/src/openrct2-ui/CursorRepository.h:12: In file included from /usr/local/include/SDL2/SDL.h:35: /usr/local/include/SDL2/SDL_atomic.h:243:28: error: '__ARM_ARCH__' is not defined, evaluates to 0 [-Werror,-Wundef] #elif (defined(__arm__) && __ARM_ARCH__ >= 7) || defined(__aarch64__)`

### CODE REVIEW

**Comment by sezero** [comment]
With this patch, the same error with similar build parameters will happen for
`__ARM_ARCH__` if it is not defined, will it not?

Maybe we need some magic defining `__ARM_ARCH` to `__ARM_ARCH__` if
the first is defined and the latter is not?

**Comment by ericoporto** [comment]
if should check if `__ARM_ARCH__` is defined before testing for it's value, otherwise it breaks what was fixed in https://github.com/libsdl-org/SDL/commit/ac44b22a24909812c50d950ba9fa02518ae177b8 (for me in Android Studio 2021.2.1 Patch 2)

**Comment by slouken** [comment]
It sounds like this is taken care of. Thanks!
