### PR TITLE
Added Emscripten support for Sensor API

### PR DESCRIPTION
**Pull request by antonegas**
## Description
Adds support for device accelerometer and gyroscope sensor on Emscripten targets, using devicemotion callback.

## Existing Issue(s)
[#13359](https://github.com/libsdl-org/SDL/issues/13359)

### CODE REVIEW

**Comment by antonegas** [comment]
I notice now that there was a minus sign left from testing which slipped through, but that should be the last adjustment.

**Comment by slouken** [comment]
Did you confirm that these axes match the SDL definitions?
https://github.com/libsdl-org/SDL/blob/7381a2b072d8dbf6e596c45316d0eaba068d61df/include/SDL3/SDL_sensor.h#L87-L126

**Comment by antonegas** [comment]
Based on my testing the axes matches the SDL definitions. I had however applied gravity incorrectly which should now be fixed. 

Mozilla seems to have [switched the Z and X axes](https://developer.mozilla.org/en-US/docs/Web/API/DeviceMotionEvent/rotationRate) when describing rotation rate, but this implementation matches what is [defined in the W3C standard](https://www.w3.org/TR/orientation-event/#device-motion-event-rotation-rate-api).

**Comment by slouken** [comment]
Merged, thanks!

**Comment by Sackzement** [comment]
I'm getting an error after this commit.

emsdk 4.0.18

```
[ 82%] Building C object CMakeFiles/SDL3-static.dir/src/sensor/emscripten/SDL_emscriptensensor.c.o
SDL/src/sensor/emscripten/SDL_emscriptensensor.c:80:5: error: incompatible function pointer types passing
      'int (*)(int, const EmscriptenDeviceMotionEvent *, void *)' (aka 'int (*)(int, const struct EmscriptenDeviceMotionEvent *, void *)') to parameter of type 'em_devicemotion_callback_func' (aka
      'bool (*)(int, const struct EmscriptenDeviceMotionEvent *, void *)') [-Wincompatible-function-pointer-types]
   80 |     emscripten_set_devicemotion_callback((void *)0, false, &SDL_EMSCRIPTEN_SensorCallback);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by antonegas** [comment]
I had it as `bool` before but the GitHub action compiles with emsdk 3.1.35 so assumed I should target that version instead. In that version of the sdk `int` is correct. If the target emscripten version is updated it should be changed back to `bool`.

**Comment by antonegas** [comment]
Actually looking at the source code for emscripten [3.1.35](https://github.com/emscripten-core/emscripten/blob/a90c5abb489c516f59c0d16864d953d4bedd37da/system/include/emscripten/html5.h#L237), it does seem like `bool` was correct then also. I just changed it to whatever passed the GitHub action so I don't know why there is this difference.

**Comment by Sackzement** [comment]
emsdk 3.1.61 is the last version that compiles successfully.
emsdk 3.1.62 fails to compile.

**Comment by slouken** [comment]
Fixed in https://github.com/libsdl-org/SDL/commit/be1d44279c715c5ac879f5698bc604fe9070ff0c
