### ISSUE TITLE
undefined reference to `SDL_UDEV_*

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#1169]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.1
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2013-10-26 05:23:21 +0000, Gerhard Stein wrote:

> I tried to link against the most recent stable SDL2 and got this problem:
> 
> [gerstrong@gerstrong-pc test]$ make
> gcc -o checkkeys checkkeys.c -g -O2 -D_REENTRANT -I/usr/include/SDL2  -DHAVE_OPENGLES -DHAVE_OPENGL -g -lSDL2_test -pthread -lSDL2 
> /usr/lib/gcc/x86_64-unknown-linux-gnu/4.8.2/../../../../lib/libSDL2.so: undefined reference to `SDL_UDEV_Poll'
> /usr/lib/gcc/x86_64-unknown-linux-gnu/4.8.2/../../../../lib/libSDL2.so: undefined reference to `SDL_UDEV_AddCallback'
> /usr/lib/gcc/x86_64-unknown-linux-gnu/4.8.2/../../../../lib/libSDL2.so: undefined reference to `SDL_UDEV_DelCallback'
> /usr/lib/gcc/x86_64-unknown-linux-gnu/4.8.2/../../../../lib/libSDL2.so: undefined reference to `SDL_UDEV_Scan'
> /usr/lib/gcc/x86_64-unknown-linux-gnu/4.8.2/../../../../lib/libSDL2.so: undefined reference to `SDL_UDEV_Quit'
> /usr/lib/gcc/x86_64-unknown-linux-gnu/4.8.2/../../../../lib/libSDL2.so: undefined reference to `SDL_UDEV_Init'
> collect2: Fehler: ld gab 1 als Ende-Status zurÃ¼ck
> Makefile:63: recipe for target 'checkkeys' failed
> make: *** [checkkeys] Error 1
> [gerstrong@gerstrong-pc test]$ 
> 
> 
> As you see, I tried it in your test routines. Same thing happens when trying to compile another project with this lib.I'm using Arch Linux.

On 2013-10-26 05:28:45 +0000, Gerhard Stein wrote:

> Just tried SDL 2.0.0 and yeah, it doesn't have that problem.

On 2013-10-30 14:00:20 +0000, Gabriel Jacobo wrote:

> I just tried to reproduce with the 2.0.1 release, running both configure and configure --disable-libudev, and it works fine with either.
> 
> Can you provide more information to help debug this? config.log, SDL_config.h, which commands you are running to build and install both SDL and the tests?
> 
> Thanks!

On 2013-10-30 14:06:12 +0000, Gerhard Stein wrote:

> Just tried it again with:
> 
> ./configure
> 
> and then:
> 
> make
> sudo make install
> cd test
> make
> 
> everything worked with SDL 2.0.1.
> 
> Let me try to reproduce somehow. Maybe it was an issue with Arch and got somehow fixed. Sorry for bothering. I might close this issue...

On 2013-10-31 18:50:11 +0000, Gabriel Jacobo wrote:

> Feel free to reopen if you find out there was actually a problem. Thanks for the report!
