### ISSUE TITLE
hg default now fails to compile on i386 with GCC 6.3

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#2514]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Linux, x86

# Comments on the original bug report:

On 2017-07-27 01:19:43 +0000,  wrote:

> Hi
> 
> I think its commit 2ee7d2fa299b that caused the issue, the one before it allows it to compile
> 
> I am compiling it with
> ./configure --prefix=$INSTALLDIR --libdir=$INSTALLDIR/lib/$(dpkg-architecture -qDEB_HOST_MULTIARCH) --enable-wayland-shared=no
> (I might not need the --enable-wayland-shared=no anymore, seems the wayland backend has been working even with that)
> 
> 
> It seems I get the below errors
> 
>   CC     build/SDL_render_gl.lo
>   CC     build/SDL_shaders_gl.lo
> /srcbuild/SDL/src/render/SDL_yuv_mmx.c: In function 'ColorRGBDitherYV12MMX1X':
> /srcbuild/SDL/src/render/SDL_yuv_mmx.c:94:5: error: 'asm' operand has impossible constraints
>      __asm__ __volatile__ (
>      ^~~~~~~
> Makefile:400: recipe for target 'build/SDL_yuv_mmx.lo' failed
> make: *** [build/SDL_yuv_mmx.lo] Error 1
> make: *** Waiting for unfinished jobs....
> PackageCompileSource finished in 8 seconds
> 
> 
> Thanks

On 2017-08-08 22:33:00 +0000, Ryan C. Gordon wrote:

> 
> We're working on the MMX assembly issue in Bug # 3689.
> 
> --ryan.
> 
> *** This bug has been marked as a duplicate of bug 3689 ***

On 2017-08-09 04:18:23 +0000, Sam Lantinga wrote:

> YUV MMX assembly is temporarily disabled until we figure this out for the various versions of GCC, or rewrite this using MMX intrinsics.
> 
> https://hg.libsdl.org/SDL/rev/0d399e95168b
