### ISSUE TITLE
SDL 2.29.3: iOS incorrectly tries to use _iconv

### ISSUE THREAD

**Issue by AJenbo** [libsdl-org/SDL#8964]
After updating to SDL 2.29.3 from 2.28.0 DevilutionX fails to build for iOS.

I'm guessing this is related to https://github.com/libsdl-org/SDL/commit/17e62abb6dd719ec2bd997d7b49b4c1eafebba7e

Setting SDL_SYSTEM_ICONV = OFF allowed the build to pass, but this was previously not necessary.

I'm guessing iOS should also be added to this line: 
https://github.com/libsdl-org/SDL/blob/8ce6fb25131912c7e83267bff03a5d1797545d5c/CMakeLists.txt#L244

```
clang: warning: overriding '-miphoneos-version-min=9.0' option with '-target aarch64-apple-ios11.0' [-Woverriding-t-option]
Undefined symbols for architecture arm64:
  "_iconv", referenced from:
      _SDL_iconv in libSDL2.a(SDL_iconv.c.o)
     (maybe you meant: _SDL_iconv_string, _SDL_iconv_open , _SDL_iconv_close , _SDL_iconv )
  "_iconv_close", referenced from:
      _SDL_iconv_close in libSDL2.a(SDL_iconv.c.o)
     (maybe you meant: _SDL_iconv_close)
  "_iconv_open", referenced from:
      _SDL_iconv_open in libSDL2.a(SDL_iconv.c.o)
     (maybe you meant: _SDL_iconv_open)
ld: symbol(s) not found for architecture arm64
```
Full buld log: https://github.com/diasurgical/devilutionX/actions/runs/7747939817/job/21129505080?pr=6920

**Comment by slouken** [comment]
Fixed for release, thanks!

**Comment by AJenbo** [comment]
thank you :)
