### ISSUE TITLE
SDL 2.30.11 fails to build with OS X 10.9 SDK

### ISSUE THREAD

**Issue by mrpapersonic** [libsdl-org/SDL#11905]
Our CI builds fail with an error in SDL_cocoawindow.m:
```
/Users/runner/work/schismtracker/schismtracker/SDL2-2.30.11/src/video/cocoa/SDL_cocoawindow.m:750:32: error: no known class method for selector 'scheduledTimerWithTimeInterval:repeats:block:'
    liveResizeTimer = [NSTimer scheduledTimerWithTimeInterval:interval
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
That API was [added in 10.12 Sierra](https://developer.apple.com/documentation/foundation/nstimer/2091889-scheduledtimerwithtimeinterval).

There is an older and very similar API that uses object member functions instead of lambdas: https://developer.apple.com/documentation/foundation/nstimer/1412416-scheduledtimerwithtimeinterval so fixing this may be trivial.

**Comment by Starbuck5** [comment]
According to the SDL 2.26.5 release notes (https://github.com/libsdl-org/SDL/releases/tag/release-2.26.5) the minimum target is 10.11.

**Comment by mrpapersonic** [comment]
I believe that's only for xcode builds. The clang-fat.sh build script at least still builds with 10.9 runtime support, and the source file for cocoa windows actually enforces a lower minimum version (10.7):
https://github.com/libsdl-org/SDL/blob/0efeb82a28795e72594642251f1bddcb881aaa7f/src/video/cocoa/SDL_cocoawindow.m#L26

**Comment by mrpapersonic** [comment]
On another related note, it seems MacPorts has already created a patch fixing this:
https://raw.githubusercontent.com/macports/macports-ports/refs/heads/master/devel/libsdl2/files/NSTimer.patch

**Comment by mrpapersonic** [comment]
...which was merged in #11827.
