### ISSUE TITLE
2.26.0 fails to build on macOS 10.13

### ISSUE THREAD

**Issue by jmroot** [libsdl-org/SDL#6598]
macOS 10.13.6, Xcode 9.4.1 (Apple clang version 902.0.39.2)

```
In file included from /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_libsdl2/libsdl2/work/SDL2-2.26.0/src/video/cocoa/SDL_cocoametalview.m:29:
In file included from /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_libsdl2/libsdl2/work/SDL2-2.26.0/src/video/cocoa/SDL_cocoametalview.h:34:
In file included from /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_libsdl2/libsdl2/work/SDL2-2.26.0/src/video/cocoa/../SDL_sysvideo.h:31:
In file included from /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_libsdl2/libsdl2/work/SDL2-2.26.0/src/video/cocoa/../SDL_vulkan_internal.h:61:
In file included from /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_libsdl2/libsdl2/work/SDL2-2.26.0/src/video/cocoa/.././khronos/vulkan/vulkan.h:32:
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_libsdl2/libsdl2/work/SDL2-2.26.0/src/video/cocoa/.././khronos/vulkan/vulkan_metal.h:36:37: error: ARC forbids Objective-C objects in struct
    const CAMetalLayer*             pLayer;
                                    ^
```
(and a bunch of similar errors for other struct members.)

Full build log is available here: https://build.macports.org/builders/ports-10.13_x86_64-builder/builds/170130/steps/install-port/logs/stdio

**Comment by slime73** [comment]
The error is coming from here: https://github.com/libsdl-org/SDL/blob/main/src/video/khronos/vulkan/vulkan_metal.h#L29-L37

That struct definition isn't compatible with ARC as far as I know. But I don't understand why it'd work with newer SDKs, unless they implicitly add `__unsafe_unretained` there or something?

**Comment by slouken** [comment]
We can edit the files to add annotation as needed.

Maybe something like this?
```c
typedef struct VkMetalSurfaceCreateInfoEXT {
    VkStructureType                 sType;
    const void*                     pNext;
    VkMetalSurfaceCreateFlagsEXT    flags;
#if defined(__OBJC__) && defined(__has_feature) && __has_feature(objc_arc)
    const CAMetalLayer__unsafe_unretained *pLayer;
#else
    const CAMetalLayer*             pLayer;
#endif
} VkMetalSurfaceCreateInfoEXT;
```

**Comment by jmroot** [comment]
Unfortunately you can't use a function-like macro in the same expression as checking if it's defined, because the preprocessor expands all macros before doing anything else, so short-circuit evaluation won't prevent an error from occurring when the macro is undefined.

**Comment by slouken** [comment]
Okay, so does this work?
```c
typedef struct VkMetalSurfaceCreateInfoEXT {
    VkStructureType                 sType;
    const void*                     pNext;
    VkMetalSurfaceCreateFlagsEXT    flags;
#if defined(__OBJC__) && defined(__has_feature)
#if __has_feature(objc_arc)
    const CAMetalLayer __unsafe_unretained *pLayer;
#else
    const CAMetalLayer*             pLayer;
#endif
#else
    const CAMetalLayer*             pLayer;
#endif
} VkMetalSurfaceCreateInfoEXT;
```

**Comment by sezero** [comment]
> Okay, so does this work?
> 
> ```c
> typedef struct VkMetalSurfaceCreateInfoEXT {
>     VkStructureType                 sType;
>     const void*                     pNext;
>     VkMetalSurfaceCreateFlagsEXT    flags;
> #if defined(__OBJC__) && defined(__has_feature)
> #if __has_feature(objc_arc)
>     const CAMetalLayer __unsafe_unretained *pLayer;
> #else
>     const CAMetalLayer*             pLayer;
> #endif
> #else
>     const CAMetalLayer*             pLayer;
> #endif
> } VkMetalSurfaceCreateInfoEXT;
> ```

It should: it is like the same usage in SDL_syswm.h, i.e.:
https://github.com/libsdl-org/SDL/blob/SDL2/include/SDL_syswm.h#L264

**Comment by jmroot** [comment]
Thanks, that approach does fix the build. I'll make a PR.
