### ISSUE TITLE
SDL_dynapi.c doesn't compile on Windows SDKs newer than 10.0.17763.0

### ISSUE THREAD

**Issue by tomcashman** [libsdl-org/SDL#7396]
`C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um\winnt.h(2540): error C2118: negative subscript`

Seems to be regression in Windows SDK since 2018, info [here](https://developercommunity.visualstudio.com/t/negative-subscript-in-winnth-5/1533745).

Using SDK 10.0.17763.0 fixes the issue.

**Comment by sezero** [comment]
Can't reproduce in git main branch using VS 2022 17.5.1. Config:
![Screenshot 2023-03-03 153552](https://user-images.githubusercontent.com/4222725/222722424-d0305bdb-7c88-4820-a473-e98ccb6804c7.png)

**Comment by AntTheAlchemist** [comment]
I'm using the latest SDL3 source with Windows 10 SDK 10.0.20348.0 no problem. (I've rolled back to 10.0.19041.0 because the binaries were much larger with the latest SDK). 

So it's specific to Windows 11 SDK?

**Comment by slime73** [comment]
The linked bug report mentions it was only happening when user code did a certain thing (`#pragma pack(push, 1)` before #including some SDK headers). 

So it might be specific to a certain SDL version which does that, or to modified SDL code which does that.

**Comment by sezero** [comment]
> So it might be specific to a certain SDL version which does that,

very unlikely

> or to modified SDL code which does that. Or even to code unrelated to SDL, if it's being compiled together?

very possible.

This doesn't look like a problem with SDL. At the very least, we need more details
from the op.

**Comment by sezero** [comment]
@tomcashman: Still waiting for more details from you.

**Comment by tomcashman** [comment]
Apologies for the delayed reply. After a bit of digging it looks like the title using SDL2 was running on a super old version. I was able to resolve by migrating to a more modern version.

**Comment by sezero** [comment]
OK then, thanks.
