### ISSUE TITLE
Compile error on Mac OS -- SDL_mfijoystick.m

### ISSUE THREAD

**Issue by jonesmz** [libsdl-org/SDL#5319]
```
 /Users/runner/work/osp-magnum/osp-magnum/3rdparty/SDL2/src/joystick/iphoneos/SDL_mfijoystick.m:1172:16: error: implicit declaration of function 'typeof' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        __weak typeof(self) weakSelf = self;
               ^
/Users/runner/work/osp-magnum/osp-magnum/3rdparty/SDL2/src/joystick/iphoneos/SDL_mfijoystick.m:1172:16: error: expected identifier or '('
/Users/runner/work/osp-magnum/osp-magnum/3rdparty/SDL2/src/joystick/iphoneos/SDL_mfijoystick.m:1174:38: error: use of undeclared identifier 'weakSelf'
            SDL_RumbleMotor *_this = weakSelf;
                                     ^
/Users/runner/work/osp-magnum/osp-magnum/3rdparty/SDL2/src/joystick/iphoneos/SDL_mfijoystick.m:1183:38: error: use of undeclared identifier 'weakSelf'
            SDL_RumbleMotor *_this = weakSelf;
                                     ^
```

Used to work with SDL2 2.0.16.
Breaks starting on 2.0.18, still broken with 2.0.20

See CI run here: https://github.com/TheOpenSpaceProgram/osp-magnum/runs/5079603649

If there's a configuration option we need to set for this, happy to be informed.

**Comment by sezero** [comment]
Are you, by any chance, building with `-std=c99` and not `-std=gnu99`: 
https://www.programmerall.com/article/9537990497/

Maybe we should use `__typeof__` instead of `typeof` if we really want to
support such a scenario. @slouken?

**Comment by jonesmz** [comment]
At the top level project (We use SDL2 as a git submodule, and add it to our build with add_subdirectory())

we set


# Set the explicit standard revision for C and C++ code.
SET(CMAKE_C_STANDARD 11)
SET(CMAKE_C_EXTENSIONS OFF)
SET(CMAKE_C_STANDARD_REQUIRED ON)

SET(CMAKE_CXX_STANDARD 17)
SET(CMAKE_CXX_EXTENSIONS OFF)
SET(CMAKE_CXX_STANDARD_REQUIRED ON)


Several of our dependencies do override this to turn on gnu extensions, but I haven't looked to see if SDL2 does. My guess, based on your response here, is that SDL2 does not.

**Comment by sezero** [comment]
> SET(CMAKE_C_EXTENSIONS OFF)
> SET(CMAKE_CXX_EXTENSIONS OFF)

These are the source of your issue I think.

> Several of our dependencies do override this to turn on gnu extensions, but I haven't looked to see if SDL2 does. My guess, based on your response here, is that SDL2 does not.

SDL runs with the compiler defaults i.e. gnu extensions on.

**Comment by jonesmz** [comment]
> These are the source of your issue I think.

Yes, probably. But this worked until release 2.0.18. So it's a regression, even if it wasn't intended to work previously.

> SDL runs with the compiler defaults i.e. gnu extensions on.

Then your CMakeLists.txt should reflect that by applying something like
```
set_target_properties(${NAME} PROPERTIES C_EXTENSIONS ON)
```

to the targets that need the compiler extensions.

Or just 

```
SET(CMAKE_C_EXTENSIONS ON)
```

at the top of the file.

CMake variables are supposed to be scoped to the cmakelists.txt file and it's "add_subdirectories" children, so adding that to the top of the file should override whatever the parent project in the build tree set, without effecting other parts of the overall build.

**Comment by sezero** [comment]
@slouken: Is the following patch OK for this?
```diff
diff --git a/src/joystick/iphoneos/SDL_mfijoystick.m b/src/joystick/iphoneos/SDL_mfijoystick.m
index ed23842..0f81480 100644
--- a/src/joystick/iphoneos/SDL_mfijoystick.m
+++ b/src/joystick/iphoneos/SDL_mfijoystick.m
@@ -1169,7 +1169,7 @@ IOS_MFIJoystickUpdate(SDL_Joystick *joystick)
             return nil;
         }
 
-        __weak typeof(self) weakSelf = self;
+        __weak __typeof(self) weakSelf = self;
         self.engine.stoppedHandler = ^(CHHapticEngineStoppedReason stoppedReason) {
             SDL_RumbleMotor *_this = weakSelf;
             if (_this == nil) {
```

If it's OK _and_ if we really care, some emscripten code has similar use of `typeof`:
should we them change to `__typeof` too?
