### ISSUE TITLE
SDL 2.30.0 fails to build on macOS 10.10

### ISSUE THREAD

**Issue by Donione** [libsdl-org/SDL#9033]
Trying to build SDL 2.30.0 on macOS 10.10 failed with these errors:
```
/Users/build/buildbot-worker/branch-mac/build/libraries/SDL2/src/joystick/iphoneos/SDL_mfijoystick.m:252:86: error: type arguments cannot be applied to non-parameterized class 'NSDictionary'
static BOOL ElementAlreadyHandled(SDL_JoystickDeviceItem *device, NSString *element, NSDictionary<NSString *, GCControllerElement *> *elements)
                                                                                     ^           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/build/buildbot-worker/branch-mac/build/libraries/SDL2/src/joystick/iphoneos/SDL_mfijoystick.m:1142:13: error: type arguments cannot be applied to non-parameterized class 'NSDictionary'
            NSDictionary<NSString *, GCControllerElement *> *elements = controller.physicalInputProfile.elements;
            ^           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/build/buildbot-worker/branch-mac/build/libraries/SDL2/src/joystick/iphoneos/SDL_mfijoystick.m:1142:84: error: property 'physicalInputProfile' not found on object of type 'GCController *'
            NSDictionary<NSString *, GCControllerElement *> *elements = controller.physicalInputProfile.elements;
                                                                                   ^
/Users/build/buildbot-worker/branch-mac/build/libraries/SDL2/src/joystick/iphoneos/SDL_mfijoystick.m:1143:13: error: type arguments cannot be applied to non-parameterized class 'NSDictionary'
            NSDictionary<NSString *, GCControllerButtonInput *> *buttons = controller.physicalInputProfile.buttons;
            ^           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/build/buildbot-worker/branch-mac/build/libraries/SDL2/src/joystick/iphoneos/SDL_mfijoystick.m:1143:87: error: property 'physicalInputProfile' not found on object of type 'GCController *'
            NSDictionary<NSString *, GCControllerButtonInput *> *buttons = controller.physicalInputProfile.buttons;
                                                                                      ^
/Users/build/buildbot-worker/branch-mac/build/libraries/SDL2/src/joystick/iphoneos/SDL_mfijoystick.m:1163:42: error: property 'isPressed' not found on object of type 'id'
                    value = buttons[key].isPressed;
                                         ^
``` 
Cherry-picking the fix for https://github.com/libsdl-org/SDL/issues/8979 brought it down to just
```
/Users/build/buildbot-worker/branch-mac/build/libraries/SDL2/src/joystick/iphoneos/SDL_mfijoystick.m:252:86: error: type arguments cannot be applied to non-parameterized class 'NSDictionary'
static BOOL ElementAlreadyHandled(SDL_JoystickDeviceItem *device, NSString *element, NSDictionary<NSString *, GCControllerElement *> *elements)
                                                                                     ^           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
``` 
Given that the `ElementAlreadyHandled` function is called only from code guarded by `ENABLE_PHYSICAL_INPUT_PROFILE` I went ahead and locally applied this change:
```diff
diff --git a/libraries/SDL2/src/joystick/iphoneos/SDL_mfijoystick.m b/libraries/SDL2/src/joystick/iphoneos/SDL_mfijoystick.m
index 62170e1f315..6eb142e729f 100644
--- a/libraries/SDL2/src/joystick/iphoneos/SDL_mfijoystick.m
+++ b/libraries/SDL2/src/joystick/iphoneos/SDL_mfijoystick.m
@@ -249,6 +249,7 @@ static void CheckControllerSiriRemote(GCController *controller, int *is_siri_rem
     *is_siri_remote = 0;
 }
 
+#ifdef ENABLE_PHYSICAL_INPUT_PROFILE
 static BOOL ElementAlreadyHandled(SDL_JoystickDeviceItem *device, NSString *element, NSDictionary<NSString *, GCControllerElement *> *elements)
 {
     if ([element isEqualToString:@"Left Thumbstick Left"] ||
@@ -347,6 +348,7 @@ static BOOL ElementAlreadyHandled(SDL_JoystickDeviceItem *device, NSString *elem
     }
     return FALSE;
 }
+#endif
 
 static BOOL IOS_AddMFIJoystickDevice(SDL_JoystickDeviceItem *device, GCController *controller)
 {
``` 
which successfully compiles and shouldn't break anything.
However, I know nothing about macOS, I'm just reading what comes from our build server, so I'm not sure if this "fix" is valid. Thoughts? @jmroot

**Comment by jmroot** [comment]
Not sure what the difference is, but we had a successful build on 10.10 after applying 2f2b44a and 8386dad: https://build.macports.org/builders/ports-10.10_x86_64-builder/builds/256083

**Comment by slouken** [comment]
That change makes sense. I've applied it and merged it through to release-2.30.x.
