### PR TITLE
[PS2] Implement joystick hotplugging

### LINKED ISSUE #16214: [PS2] SDL_EVENT_GAMEPAD_ADDED sent for unplugged controllers, causing hang when opened
The PS2 backend [sends SDL_EVENT_GAMEPAD_ADDED events for all 8 gamepad slots](https://github.com/libsdl-org/SDL/blob/46498bc247819a2da7c1ccc7d4c4f6231076666c/src/joystick/ps2/SDL_sysjoystick.c#L123) immediately on startup, regardless of whether the corresponding controller is actually connected. Attempting to call SDL_OpenGamepad on them causes PS2_InitializePad to [wait until the controller is actually plugged in](https://github.com/libsdl-org/SDL/blob/46498bc247819a2da7c1ccc7d4c4f6231076666c/src/joystick/ps2/SDL_sysjoystick.c#L211).

Note: I do not own a physical PS2 to confirm the issue on. This behavior was observed in PCSX2 v2.6.3

## Steps to reproduce
1. Poll for SDL_EVENT_GAMEPAD_ADDED events;
2. Call SDL_OpenGamepad on the added controllers.

## Expected result
Controllers that are plugged in are opened.
Controllers that are not plugged in on startup are opened once they are plugged in.

## Actual result
The application hangs and does not recover until all 8 controller slots are occupied.

## Suggested fix
Send SDL_EVENT_GAMEPAD_ADDED events when controllers are plugged in, rather than on startup.

## Minimal reproduction

[main.c](https://github.com/user-attachments/files/31605987/main.c)

[CMakeLists.txt](https://github.com/user-attachments/files/31605986/CMakeLists.txt)

### PR DESCRIPTION
**Pull request by Sawkez**
- [x] I confirm that I am the author of this code and release it to the SDL project under the zlib license. This contribution does not contain code from other sources, including code generated by a Large Language Model ("AI").

Call `SDL_PrivateJoystickAdded` when joysticks are plugged in, rather than on startup on the PS2 backend.

## Description
Previously, the PS2 backend would call `SDL_PrivateJoystickAdded` for all 8 controller ports on startup, regardless of whether the corresponding controller is actually plugged in. Calling `SDL_OpenGamepad` on the added gamepads would cause the app to hang until they are plugged in.
These changes allow the backend to add controllers as they are plugged in.

`PS2_WaitPadReady` now returns if the controller is disconnected.
`PS2_JoystickDetect` now polls for which controllers are plugged in.
Joystick instance IDs are now assigned in the order the controllers are connected. A lookup array (`joyInfoByIndex`) is used to get back the `JoyInfo` for the corresponding instance ID.

This does not implement calling `SDL_PrivateJoystickRemoved` when controllers are unplugged.
This has not been tested on real hardware, but works on PCSX2 v2.8.2

## Existing Issue(s)
Fixes #16214

### CODE REVIEW

**Comment by slouken** [comment]
Merged, thanks!
