### ISSUE TITLE
SDL 2.24.0+ compilation error on macOs when generating Xcode project with cmake

### ISSUE THREAD

**Issue by dashandslash** [libsdl-org/SDL#6197]
I am using SDL in a project, and after updating SDL to version 2.24.0 from 2.0.20, generating the Xcode project using CMake gives build errors 

![image](https://user-images.githubusercontent.com/920858/188859462-12bcc8bf-5e56-4e1a-a970-ccd32e9b6310.png)

I manage to fix this issue by adapting the SDL CMakeLists.txt here: https://github.com/dashandslash/SDL/tree/fix-compilation-on-osx-with-cmake-xcode-project-generation

Has anyone else had the same issue?

**Comment by dashandslash** [comment]
I opened a PR that seems to fix this issue:
https://github.com/libsdl-org/SDL/pull/6198

**Comment by madebr** [comment]
Fixed in https://github.com/libsdl-org/SDL/pull/6455
