### ISSUE TITLE
possible API break for applications declaring main() with no arguments

### ISSUE THREAD

**Issue by smcv** [libsdl-org/SDL#14580]
[C23](https://en.wikipedia.org/wiki/C23_(C_standard_revision)) says `main()` may be declared as `int main (void)` or `int main (int argc, char *argv[])` or "in some other implementation-defined manner", and earlier revisions have similar wording.

I used this in a smoke-test to make sure that the Debian packaging's `libsdl3-dev` doesn't regress:

```sh
export SDL_AUDIO_DRIVER=dummy
export SDL_VIDEO_DRIVER=dummy

cd "$WORKDIR"
cat <<EOF > use-sdl.c
#undef NDEBUG
#include <assert.h>

#include <SDL3/SDL.h>
#include <SDL3/SDL_main.h>

int main(void)
{
    int compiled = SDL_VERSION;
    int linked = SDL_GetVersion();

    SDL_Log("Compiled against version %d\n", compiled);
    SDL_Log("Now running with version %d (%s)\n", linked, SDL_GetRevision());

    assert(SDL_VERSIONNUM_MAJOR(compiled) == 3);
    assert(SDL_VERSIONNUM_MAJOR(linked) == 3);

    return 0;
}
EOF

...

"$cc" $cflags -o "${exe}" use-sdl.c $("${CROSS_COMPILE}pkgconf" --cflags --libs sdl3)
```

This worked with 3.2.x, but not with 3.3 prereleases:

```
+ gcc -o use-gcc use-sdl.c -D_REENTRANT -I/usr/include/fribidi -I/usr/include/libdrm -I/usr/include/libdecor-0 -lSDL3
In file included from /usr/include/SDL3/SDL_main.h:684,
                 from use-sdl.c:5:
use-sdl.c:7:5: error: conflicting types for ‘SDL_main’; have ‘int(void)’
    7 | int main(void)
      |     ^~~~
/usr/include/SDL3/SDL_main.h:538:37: note: previous declaration of ‘SDL_main’ with type ‘int(int,  char **)’
  538 | extern SDLMAIN_DECLSPEC int SDLCALL SDL_main(int argc, char *argv[]);
      |                                     ^~~~~~~~
```

I recognise that this is a corner case, especially since SDL 3 is not yet widely adopted, but I thought I should raise this as something that could potentially break previously-considered-correct code.

**Comment by smcv** [comment]
> in some other implementation-defined manner

For example on at least Linux (probably some other Unixes too), as an extension, `int main (int argc, char *argv[], char *envp[])` is considered equally correct.

**Comment by smcv** [comment]
Guessing this is something to do with #14555. Presumably it could be worked around by defining `SDL_MAIN_HANDLED`.

**Comment by smcv** [comment]
Sorry, I initially pasted the wrong version of the smoke test. The right version declares `int main(void)`.

**Comment by madebr** [comment]
`int main(void)` did never work for SDL2 when using a MinGW toolchain:
```
$ i686-w64-mingw32-gcc a.c -lSDL2
In file included from /usr/i686-w64-mingw32/sys-root/mingw/include/SDL2/SDL.h:31,
                 from a.c:1:
a.c:2:5: error: conflicting types for 'SDL_main'; have 'int(void)'
    2 | int main(void)
      |     ^~~~
/usr/i686-w64-mingw32/sys-root/mingw/include/SDL2/SDL_main.h:155:29: note: previous declaration of 'SDL_main' with type 'int(int,  char **)'
  155 | extern SDLMAIN_DECLSPEC int SDL_main(int argc, char *argv[]);
      |                             ^~~~~~~~
maarten@blocked:/tmp$ x86_64-w64-mingw32-gcc a.c -lSDL2
In file included from /usr/x86_64-w64-mingw32/sys-root/mingw/include/SDL2/SDL.h:31,
                 from a.c:1:
a.c:2:5: error: conflicting types for 'SDL_main'; have 'int(void)'
    2 | int main(void)
      |     ^~~~
/usr/x86_64-w64-mingw32/sys-root/mingw/include/SDL2/SDL_main.h:155:29: note: previous declaration of 'SDL_main' with type 'int(int,  char **)'
  155 | extern SDLMAIN_DECLSPEC int SDL_main(int argc, char *argv[]);
      |                             ^~~~~~~~
```

**Comment by slouken** [comment]
After thinking this through, I think we'll leave this as-is and document that if you want an alternate main entry point then you should define `SDL_MAIN_HANDLED` and call SDL_SetMainReady(). This is related to https://github.com/libsdl-org/SDL/issues/14513.

**Comment by smcv** [comment]
> `int main(void)` did never work for SDL2 when using a MinGW toolchain

Sure, but it did work on Linux, and probably other platforms, so I thought I should raise this.

> I think we'll leave this as-is and document that if you want an alternate main entry point then you should define `SDL_MAIN_HANDLED` and call SDL_SetMainReady()

Yeah, that seems reasonable.

**Comment by smcv** [comment]
Likely related, a test program that previously worked:

```cpp
// Copyright 2022 quyykk
// SPDX-License-Identifer: Zlib

#include <iostream>
#include <SDL3/SDL.h>
#include <SDL3/SDL_main.h>

int main()
{
	if(!SDL_Init(SDL_INIT_VIDEO))
		return -1;

	std::cout << "initialized!\n";
	return 0;
}
```

```cmake
# Copyright 2022 quyykk
# SPDX-License-Identifier: Zlib

cmake_minimum_required(VERSION 3.13)

project(Test LANGUAGES CXX)

find_package(SDL3 CONFIG REQUIRED)
add_executable(program test.cpp)
target_link_libraries(program PRIVATE SDL3::SDL3)
```

is now failing to link:

```
261s /usr/bin/c++    -MD -MT CMakeFiles/program.dir/test.cpp.o -MF CMakeFiles/program.dir/test.cpp.o.d -o CMakeFiles/program.dir/test.cpp.o -c /tmp/autopkgtest.RnwZ7V/build.A8m/src/debian/tests/cmake-main/test.cpp
262s [100%] Linking CXX executable program
262s /usr/bin/cmake -E cmake_link_script CMakeFiles/program.dir/link.txt --verbose=1
262s /usr/bin/ld: CMakeFiles/program.dir/test.cpp.o: in function `main':
262s test.cpp:(.text+0x12): undefined reference to `SDL_main'
262s collect2: error: ld returned 1 exit status                                   
262s make[2]: *** [CMakeFiles/program.dir/build.make:102: program] Error 1        
262s make[1]: *** [CMakeFiles/Makefile2:87: CMakeFiles/program.dir/all] Error 2   
262s make: *** [Makefile:91: all] Error 2                                         
262s /usr/bin/c++ -Wl,--dependency-file=CMakeFiles/program.dir/link.d CMakeFiles/program.dir/test.cpp.o -o program  /usr/lib/x86_64-linux-gnu/libSDL3.so.0.3.3
262s make[2]: Leaving directory '/tmp/tmp.Rw9qbka0hC/main'                        
262s make[1]: Leaving directory '/tmp/tmp.Rw9qbka0hC/main'                        
262s make: Leaving directory '/tmp/tmp.Rw9qbka0hC/main'                           
```

**Comment by smcv** [comment]
This C++ test originated from https://github.com/ValveSoftware/steam-runtime/issues/537#issuecomment-1266172655 (it was originally for SDL2, I adapted it for SDL3).

**Comment by slouken** [comment]
If you define `SDL_MAIN_HANDLED` and make no other changes, does the test program succeed? Looking at the code, SDL_Init() should fail in this case.

**Comment by smcv** [comment]
Both test-cases https://github.com/libsdl-org/SDL/issues/14580#issue-3691029771 and https://github.com/libsdl-org/SDL/issues/14580#issuecomment-3608274471 succeed if I `#define SDL_MAIN_HANDLED` before including SDL headers.

Both also succeed if I revert the addition of `#define SDL_MAIN_HANDLED`, and instead change the declaration of `main` to `int main (int argc, char *argv[])`.

**Comment by slouken** [comment]
I went ahead and reverted that change, since it's more likely to confuse people with the API change than help people who care that the main thread is set when not using SDL_Init().

**Comment by slouken** [comment]
Thanks for the heads up!

**Comment by smcv** [comment]
> I went ahead and reverted that change, since it's more likely to confuse people with the API change than help people who care that the main thread is set when not using SDL_Init().

Thanks, that seems sensible. If you have a list of incompatible changes being saved up for SDL 4, this could be added there if you want - it would be fine for SDL 4 to be more strict about this than SDL 3 was.
