### PR TITLE
vulkan_metal.h: Make compatible with ObjC ARC

### LINKED ISSUE #6598: 2.26.0 fails to build on macOS 10.13
macOS 10.13.6, Xcode 9.4.1 (Apple clang version 902.0.39.2)

```
In file included from /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_libsdl2/libsdl2/work/SDL2-2.26.0/src/video/cocoa/SDL_cocoametalview.m:29:
In file included from /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_libsdl2/libsdl2/work/SDL2-2.26.0/src/video/cocoa/SDL_cocoametalview.h:34:
In file included from /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_libsdl2/libsdl2/work/SDL2-2.26.0/src/video/cocoa/../SDL_sysvideo.h:31:
In file included from /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_libsdl2/libsdl2/work/SDL2-2.26.0/src/video/cocoa/../SDL_vulkan_internal.h:61:
In file included from /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_libsdl2/libsdl2/work/SDL2-2.26.0/src/video/cocoa/.././khronos/vulkan/vulkan.h:32:
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_libsdl2/libsdl2/work/SDL2-2.26.0/src/video/cocoa/.././khronos/vulkan/vulkan_metal.h:36:37: error: ARC forbids Objective-C objects in struct
    const CAMetalLayer*             pLayer;
                                    ^
```
(and a bunch of similar errors for other struct members.)

Full build log is available here: https://build.macports.org/builders/ports-10.13_x86_64-builder/builds/170130/steps/install-port/logs/stdio

### PR DESCRIPTION
**Pull request by jmroot**
Fixes #6598

## Description
ARC, at least with older compilers and/or SDKs, doesn't allow Objective-C objects in structs without declaring them `__unsafe_unretained`.

## Existing Issue(s)
https://github.com/libsdl-org/SDL/issues/6598

### CODE REVIEW

**Comment by sezero** [comment]
If we do apply this patch, we have to remember re-applying upon any future syncing with khronos.

**Comment by jmroot** [comment]
Maybe khronos would accept a similar patch? In the meantime, would it be helpful to start a directory of patches applied to third party code?
