### ISSUE TITLE
SDL 2.24.0 fails to build on macOS < 10.14

### ISSUE THREAD

**Issue by jmroot** [libsdl-org/SDL#6089]
The failing compile command and error are:
```
libtool: compile:  /usr/bin/clang -pipe -Os -arch x86_64 -I/opt/local/include -DUSING_GENERATED_CONFIG_H -Iinclude -I/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_libsdl2/libsdl2/work/SDL2-2.24.0/include -idirafter /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_libsdl2/libsdl2/work/SDL2-2.24.0/src/video/khronos -DSDL_BUILD_MAJOR_VERSION=2 -DSDL_BUILD_MINOR_VERSION=24 -DSDL_BUILD_MICRO_VERSION=0 -mmmx -m3dnow -msse -msse2 -msse3 -Wall -fno-strict-aliasing -DTARGET_API_MAC_CARBON -DTARGET_API_MAC_OSX -fobjc-arc -fvisibility=hidden -Wdeclaration-after-statement -Werror=declaration-after-statement -DMESA_EGL_NO_X11_HEADERS -DEGL_NO_X11 -D_THREAD_SAFE -MMD -MT build/SDL_cocoashape.lo -c /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_libsdl2/libsdl2/work/SDL2-2.24.0/src/video/cocoa/SDL_cocoashape.m  -fno-common -DPIC -o build/.libs/SDL_cocoashape.o

In file included from /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_libsdl2/libsdl2/work/SDL2-2.24.0/src/video/cocoa/SDL_cocoashape.m:27:
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_libsdl2/libsdl2/work/SDL2-2.24.0/src/video/cocoa/SDL_cocoashape.h:33:24: error: ARC forbids Objective-C objects in struct
    NSGraphicsContext* context;
                       ^
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_devel_libsdl2/libsdl2/work/SDL2-2.24.0/src/video/cocoa/SDL_cocoashape.m:61:13: error: ARC forbids Objective-C objects in struct
    NSView* view;
            ^
```

Full build output for 10.13 is available here: https://build.macports.org/builders/ports-10.13_x86_64-builder/builds/160213/steps/install-port/logs/stdio

**Comment by slime73** [comment]
I can see why this is broken, but I don't understand why it didn't appear in #5954 - @sezero have you had successful macOS builds on one of these older OS versions recently?

**Comment by sezero** [comment]
> I can see why this is broken, but I don't understand why it didn't appear in #5954 (or why it would work in newer SDK versions) - @sezero have you had successful macOS builds on one of these older OS versions recently?

Haven't attempted building for mac since #5954, but my builds back then were successful and I don't think the structures have changed since.
