### ISSUE TITLE
sdl2 2.0.20 fails to build for conda-forge

### ISSUE THREAD

**Issue by matham** [libsdl-org/SDL#5208]
I am trying to update the conda-forge sdl2 package to v2.0.20 and I ran into an error building on the CI. The error is:

```
 CC     build/SDL_cocoamodes.lo
/Users/runner/miniforge3/conda-bld/sdl2_1641874445214/work/src/video/cocoa/SDL_cocoamodes.m:304:32: warning: 'CGDisplayIOServicePort' is deprecated: first deprecated in macOS 10.9 [-Wdeprecated-declarations]
    io_service_t servicePort = CGDisplayIOServicePort(displayID);
                               ^
/Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGDisplayConfiguration.h:355:24: note: 'CGDisplayIOServicePort' has been explicitly marked deprecated here
CG_EXTERN io_service_t CGDisplayIOServicePort(CGDirectDisplayID display)
                       ^
/Users/runner/miniforge3/conda-bld/sdl2_1641874445214/work/src/video/cocoa/SDL_cocoamodes.m:480:58: error: use of undeclared identifier 'kDisplayModeNativeFlag'
                        if (CGDisplayModeGetIOFlags(m) & kDisplayModeNativeFlag) {
                                                         ^
1 warning and 1 error generated.
make: *** [Makefile:636: build/SDL_cocoamodes.lo] Error 1
```
Here's the [full log](https://github.com/libsdl-org/SDL/files/7843738/build.txt). You can also see it in [this PR](https://github.com/conda-forge/sdl2-feedstock/pull/23).

This variable (`kDisplayModeNativeFlag`) seems to have been introduced very recently.

**Comment by slouken** [comment]
@vkedwardli, can you look at this?

**Comment by vkedwardli** [comment]
Sorry that my https://github.com/libsdl-org/SDL/pull/5135 is the root cause for this issue.

I have tried to use `MacOSX10.9.sdk` with Xcode 12.4, following your [download_osx_sdk.sh](https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/master/recipe/download_osx_sdk.sh) (adding the 10.9 SDK and manual editing Xcode's `MinimumSDKVersion`)

Self defining the flag seems to be working. 

But @matham I'm a bit curious how can you link the CoreHaptics.framework with `MacOSX10.9.sdk` (available since macOS 10.15) or Metal.framework (available since macOS 10.11)?

![image](https://user-images.githubusercontent.com/602245/148909358-a1d90354-d982-4f70-9d96-28eaa42e8bde.png)

**Comment by sezero** [comment]
I hit the error if I build against 10.8 SDK, but 10.9 is OK because that
`kDisplayModeNativeFlag` enum value is in my 10.9 SDK (10.9.5 to be
precise), so I can apply this:
```diff
diff --git a/src/video/cocoa/SDL_cocoamodes.m b/src/video/cocoa/SDL_cocoamodes.m
index e8ce12d86..dc2535947 100644
--- a/src/video/cocoa/SDL_cocoamodes.m
+++ b/src/video/cocoa/SDL_cocoamodes.m
@@ -40,6 +40,9 @@
 #ifndef MAC_OS_X_VERSION_10_13
 #define NSAppKitVersionNumber10_12 1504
 #endif
+#ifndef MAC_OS_X_VERSION_10_9
+#define kDisplayModeNativeFlag 0x02000000
+#endif
 
 
 static void
```

HOWEVER: The error @matham reports shows that he _is_ building against
10.9 SDK: Is that enum value added in later iterations of 10.9?

**Comment by sezero** [comment]
https://github.com/alexey-lysiuk/macos-sdk/commit/26f21376121afa205220415eb26ac9307c1beb61#diff-457e24a7cf314568f62e7e51be1108c1f7a948cacd41990f7e17329c77065203
shows that it isn't available with `IOGRAPHICSTYPES_REV 38`,
but it is with `IOGRAPHICSTYPES_REV 40`.  Don't know about a
possible `39`. What is the best solution here?

**Comment by sezero** [comment]
I suggest the easiest and lazy solution as the following:
```diff
diff --git a/src/video/cocoa/SDL_cocoamodes.m b/src/video/cocoa/SDL_cocoamodes.m
index e8ce12d..92cca36 100644
--- a/src/video/cocoa/SDL_cocoamodes.m
+++ b/src/video/cocoa/SDL_cocoamodes.m
@@ -41,6 +41,10 @@
 #define NSAppKitVersionNumber10_12 1504
 #endif
 
+#if !defined(MAC_OS_X_VERSION_10_9) || (IOGRAPHICSTYPES_REV < 40)
+#define kDisplayModeNativeFlag 0x02000000
+#endif
+
 
 static void
 Cocoa_ToggleMenuBar(const BOOL show)
```

**Comment by sezero** [comment]
Just pushed ea0bca573da796268900e53d74541dfe279bb662 for this.  If there are any further issues with this, then reopen and continue discussion.

**Comment by vkedwardli** [comment]
> Is that enum value added in later iterations of 10.9

It is added in [10.9.3](https://opensource.apple.com/release/os-x-1093.html) (IOGraphics-471.4, `IOGRAPHICSTYPES_REV` = 40)

**Comment by sezero** [comment]
You're welcome.
