### ISSUE TITLE
Build error on Fedora 17

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#589]
# This bug report was migrated from our old Bugzilla tracker.

These attachments are available in the static archive:

* [config.log of failed "checking for const parameter to XextAddDisplay" detection on Fedora 17 (config.log, text/plain, 2012-06-02 06:57:39 +0000, 208882 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=866)
* [config.log of failed "checking for const parameter to XextAddDisplay" detection on Fedora 17 from older SDL rev 698c98b83cbb (config.log, text/plain, 2012-06-02 07:38:51 +0000, 209168 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=867)
* [/usr/include/X11/extensions/extutil.h header file as present on my Fedora 17 system (extutil.h, text/plain, 2012-06-02 09:16:30 +0000, 6071 bytes)](https://bugzilla.libsdl.org/attachment.cgi?id=868)

**Reported in version:** HG 2.0
**Reported for operating system, platform:** Linux, x86_64

# Comments on the original bug report:

On 2012-05-15 11:07:00 +0000, Ellie wrote:

> It seems in Fedora 17, some Xext things changed which causes trouble for SDL:
> 
> /bin/sh ./libtool --mode=compile gcc -g -O3 -DUSING_GENERATED_CONFIG_H -I./include  -mmmx -m3dnow -msse -msse2 -fvisibility=hidden  -D_REENTRANT -DHAVE_LINUX_VERSION_H -Wall -MMD -MT build/SDL_x11dyn.lo -c src/video/x11/SDL_x11dyn.c -o build/SDL_x11dyn.lo
> libtool: compile:  gcc -g -O3 -DUSING_GENERATED_CONFIG_H -I./include -mmmx -m3dnow -msse -msse2 -fvisibility=hidden -D_REENTRANT -DHAVE_LINUX_VERSION_H -Wall -MMD -MT build/SDL_x11dyn.lo -c src/video/x11/SDL_x11dyn.c -o build/SDL_x11dyn.o
> In file included from src/video/x11/SDL_x11dyn.c:110:0:
> src/video/x11/SDL_x11sym.h:106:151: error: conflicting types for âXextAddDisplayâ
> In file included from src/video/x11/SDL_x11dyn.h:38:0,
>                  from src/video/x11/SDL_x11dyn.c:27:
> /usr/include/X11/extensions/extutil.h:123:25: note: previous declaration of âXextAddDisplayâ was here
> make[2]: *** [build/SDL_x11dyn.lo] Error 1
> 
> No problem on Fedora 16.
> Line 123+ from /usr/include/X11/extensions/extutil.h:
> 
> extern XExtDisplayInfo *XextAddDisplay(
>     XExtensionInfo* /* extinfo */,
>     Display*        /* dpy */,
>     _Xconst char*   /* ext_name */,
>     XExtensionHooks*    /* hooks */,
>     int         /* nevents */,
>     XPointer        /* data */
> );

On 2012-05-16 02:12:37 +0000, Ellie wrote:

> I just tested a fix which is indeed trivial:
> 
> SDL_x11sym.h line 106 originally looks like this:
> 
> SDL_X11_SYM(XExtDisplayInfo*,XextAddDisplay,(XExtensionInfo* a,Display* b,char* c,XExtensionHooks* d,int e,XPointer f),(a,b,c,d,e,f),return)
> 
> To build on Fedora 17, it needs to look like this:
> 
> SDL_X11_SYM(XExtDisplayInfo*,XextAddDisplay,(XExtensionInfo* a,Display* b,const char* c,XExtensionHooks* d,int e,XPointer f),(a,b,c,d,e,f),return)

On 2012-05-21 07:52:00 +0000, Manuel BÃ¤renz wrote:

> Will this be changed in the near future?

On 2012-05-30 08:46:05 +0000, Sam Lantinga wrote:

> This should be fixed in this changeset:
> http://hg.libsdl.org/SDL/rev/d86efd889847
> 
> Can you verify?

On 2012-06-01 15:53:51 +0000, Gabriel Jacobo wrote:

> There was a problem on my Ubuntu system which had the old headers (the test never failed!) http://hg.libsdl.org/SDL/rev/698c98b83cbb

On 2012-06-02 06:56:12 +0000, Ellie wrote:

> Apparently not fixed on Fedora 17 with a checkout I did 5 minutes ago.
> 
> Basically, it seems from the given error line 109 in SDL_x11sym.h that SDL_VIDEO_DRIVER_X11_CONST_PARAM_XEXTADDDISPLAY isn't defined, and therefore the #else path is taken and the problem persists.
> 
> From the config log, the test "checking for const parameter to XextAddDisplay" returned "no" (which is wrong). Will attach config.log, hopefully that will shed light on the problem.

On 2012-06-02 06:57:39 +0000, Ellie wrote:

> Created attachment 866
> config.log of failed "checking for const parameter to XextAddDisplay" detection on Fedora 17

On 2012-06-02 07:00:13 +0000, Gabriel Jacobo wrote:

> Would you try again with this revision instead of the latest? http://hg.libsdl.org/SDL/rev/698c98b83cbb

On 2012-06-02 07:37:37 +0000, Ellie wrote:

> "checking for const parameter to XextAddDisplay" also broken in rev 698c98b83cbb, despite with other config.log code and error.

On 2012-06-02 07:38:51 +0000, Ellie wrote:

> Created attachment 867
> config.log of failed "checking for const parameter to XextAddDisplay" detection on Fedora 17 from older SDL rev 698c98b83cbb

On 2012-06-02 07:44:26 +0000, Gabriel Jacobo wrote:

> Can you post the contents of /usr/include/X11/extensions/extutil.h in your system, I don't have a Fedora system so it'll be easier for me to make the test work fine with that file.

On 2012-06-02 09:16:30 +0000, Ellie wrote:

> Created attachment 868
> /usr/include/X11/extensions/extutil.h header file as present on my Fedora 17 system

On 2012-06-03 13:37:07 +0000, Gabriel Jacobo wrote:

> Can you test? http://hg.libsdl.org/SDL/rev/7c37af802e63
> 
> I've tested with my Ubuntu 12.04 headers, the test fails with:
> 
> configure:18626: checking for const parameter to XextAddDisplay
> configure:18647: gcc -c -g -O2 -I./include    -I./include  conftest.c >&5
> conftest.c:124:39: error: conflicting types for 'XextAddDisplay'
> /usr/include/X11/extensions/extutil.h:123:25: note: previous declaration of 'XextAddDisplay' was here
> 
> 
> With your header file it succeeds:
> 
> configure:18626: checking for const parameter to XextAddDisplay
> configure:18647: gcc -c -g -O2 -I./include    -I./include  conftest.c >&5
> configure:18647: $? = 0
> configure:18655: result: yes

On 2012-06-05 02:21:00 +0000, Ellie wrote:

> Rev. 7c37af802e63 compiles well here:
> 
> checking for const parameter to XextAddDisplay... yes
