### ISSUE TITLE
[Build failure] Latest revision won't build due to error in SDL_waylandvideo.c

### ISSUE THREAD

**Issue by ell1e** [libsdl-org/SDL#4584]
I wanted to test the fix for #3689 and while it seems to have worked, I ran into a new problem on https://github.com/libsdl-org/SDL/commit/1907463a7e876d0aec1d2a87839ec8b9b30d64d2:
```
  CC     build/SDL_waylandclipboard.lo
In file included from /tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylanddatamanager.h:27,
                 from /tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandclipboard.c:25:
/tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandvideo.h:95:49: warning: 'struct wl_surface' declared inside parameter list will not be visible outside of this definition or declaration
   95 | extern void SDL_WAYLAND_register_surface(struct wl_surface *surface);
      |                                                 ^~~~~~~~~~
/tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandvideo.h:97:48: warning: 'struct wl_surface' declared inside parameter list will not be visible outside of this definition or declaration
   97 | extern SDL_bool SDL_WAYLAND_own_surface(struct wl_surface *surface);
      |                                                ^~~~~~~~~~
  CC     build/SDL_waylanddatamanager.lo
In file included from /tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylanddatamanager.c:34:
/tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandvideo.h:95:49: warning: 'struct wl_surface' declared inside parameter list will not be visible outside of this definition or declaration
   95 | extern void SDL_WAYLAND_register_surface(struct wl_surface *surface);
      |                                                 ^~~~~~~~~~
/tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandvideo.h:97:48: warning: 'struct wl_surface' declared inside parameter list will not be visible outside of this definition or declaration
   97 | extern SDL_bool SDL_WAYLAND_own_surface(struct wl_surface *surface);
      |                                                ^~~~~~~~~~
  CC     build/SDL_waylanddyn.lo
  CC     build/SDL_waylandevents.lo
In file included from /tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandevents.c:34:
/tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandvideo.h:95:49: warning: 'struct wl_surface' declared inside parameter list will not be visible outside of this definition or declaration
   95 | extern void SDL_WAYLAND_register_surface(struct wl_surface *surface);
      |                                                 ^~~~~~~~~~
/tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandvideo.h:97:48: warning: 'struct wl_surface' declared inside parameter list will not be visible outside of this definition or declaration
   97 | extern SDL_bool SDL_WAYLAND_own_surface(struct wl_surface *surface);
      |                                                ^~~~~~~~~~
/tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandevents.c: In function 'pointer_handle_enter':
/tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandevents.c:280:34: warning: passing argument 1 of 'SDL_WAYLAND_own_surface' from incompatible pointer type [-Wincompatible-pointer-types]
  280 |     if (!SDL_WAYLAND_own_surface(surface)) {
      |                                  ^~~~~~~
      |                                  |
      |                                  struct wl_surface *
In file included from /tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandevents.c:34:
/tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandvideo.h:97:60: note: expected 'struct wl_surface *' but argument is of type 'struct wl_surface *'
   97 | extern SDL_bool SDL_WAYLAND_own_surface(struct wl_surface *surface);
      |                                         ~~~~~~~~~~~~~~~~~~~^~~~~~~
/tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandevents.c: In function 'pointer_handle_leave':
/tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandevents.c:313:46: warning: passing argument 1 of 'SDL_WAYLAND_own_surface' from incompatible pointer type [-Wincompatible-pointer-types]
  313 |     if (!surface || !SDL_WAYLAND_own_surface(surface)) {
      |                                              ^~~~~~~
      |                                              |
      |                                              struct wl_surface *
In file included from /tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandevents.c:34:
/tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandvideo.h:97:60: note: expected 'struct wl_surface *' but argument is of type 'struct wl_surface *'
   97 | extern SDL_bool SDL_WAYLAND_own_surface(struct wl_surface *surface);
      |                                         ~~~~~~~~~~~~~~~~~~~^~~~~~~
/tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandevents.c: In function 'keyboard_handle_enter':
/tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandevents.c:733:34: warning: passing argument 1 of 'SDL_WAYLAND_own_surface' from incompatible pointer type [-Wincompatible-pointer-types]
  733 |     if (!SDL_WAYLAND_own_surface(surface)) {
      |                                  ^~~~~~~
      |                                  |
      |                                  struct wl_surface *
In file included from /tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandevents.c:34:
/tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandvideo.h:97:60: note: expected 'struct wl_surface *' but argument is of type 'struct wl_surface *'
   97 | extern SDL_bool SDL_WAYLAND_own_surface(struct wl_surface *surface);
      |                                         ~~~~~~~~~~~~~~~~~~~^~~~~~~
/tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandevents.c: In function 'keyboard_handle_leave':
/tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandevents.c:757:46: warning: passing argument 1 of 'SDL_WAYLAND_own_surface' from incompatible pointer type [-Wincompatible-pointer-types]
  757 |     if (!surface || !SDL_WAYLAND_own_surface(surface)) {
      |                                              ^~~~~~~
      |                                              |
      |                                              struct wl_surface *
In file included from /tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandevents.c:34:
/tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandvideo.h:97:60: note: expected 'struct wl_surface *' but argument is of type 'struct wl_surface *'
   97 | extern SDL_bool SDL_WAYLAND_own_surface(struct wl_surface *surface);
      |                                         ~~~~~~~~~~~~~~~~~~~^~~~~~~
  CC     build/SDL_waylandkeyboard.lo
In file included from /tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandkeyboard.c:26:
/tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandvideo.h:95:49: warning: 'struct wl_surface' declared inside parameter list will not be visible outside of this definition or declaration
   95 | extern void SDL_WAYLAND_register_surface(struct wl_surface *surface);
      |                                                 ^~~~~~~~~~
/tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandvideo.h:97:48: warning: 'struct wl_surface' declared inside parameter list will not be visible outside of this definition or declaration
   97 | extern SDL_bool SDL_WAYLAND_own_surface(struct wl_surface *surface);
      |                                                ^~~~~~~~~~
  CC     build/SDL_waylandmessagebox.lo
  CC     build/SDL_waylandmouse.lo
In file included from /tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandmouse.c:36:
/tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandvideo.h:95:49: warning: 'struct wl_surface' declared inside parameter list will not be visible outside of this definition or declaration
   95 | extern void SDL_WAYLAND_register_surface(struct wl_surface *surface);
      |                                                 ^~~~~~~~~~
/tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandvideo.h:97:48: warning: 'struct wl_surface' declared inside parameter list will not be visible outside of this definition or declaration
   97 | extern SDL_bool SDL_WAYLAND_own_surface(struct wl_surface *surface);
      |                                                ^~~~~~~~~~
  CC     build/SDL_waylandopengles.lo
In file included from /tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandopengles.c:29:
/tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandvideo.h:95:49: warning: 'struct wl_surface' declared inside parameter list will not be visible outside of this definition or declaration
   95 | extern void SDL_WAYLAND_register_surface(struct wl_surface *surface);
      |                                                 ^~~~~~~~~~
/tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandvideo.h:97:48: warning: 'struct wl_surface' declared inside parameter list will not be visible outside of this definition or declaration
   97 | extern SDL_bool SDL_WAYLAND_own_surface(struct wl_surface *surface);
      |                                                ^~~~~~~~~~
  CC     build/SDL_waylandtouch.lo
In file included from /tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandtouch.h:29,
                 from /tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandtouch.c:30:
/tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandvideo.h:95:49: warning: 'struct wl_surface' declared inside parameter list will not be visible outside of this definition or declaration
   95 | extern void SDL_WAYLAND_register_surface(struct wl_surface *surface);
      |                                                 ^~~~~~~~~~
/tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandvideo.h:97:48: warning: 'struct wl_surface' declared inside parameter list will not be visible outside of this definition or declaration
   97 | extern SDL_bool SDL_WAYLAND_own_surface(struct wl_surface *surface);
      |                                                ^~~~~~~~~~
  CC     build/SDL_waylandvideo.lo
In file included from /tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandvideo.c:31:
/tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandvideo.h:95:49: warning: 'struct wl_surface' declared inside parameter list will not be visible outside of this definition or declaration
   95 | extern void SDL_WAYLAND_register_surface(struct wl_surface *surface);
      |                                                 ^~~~~~~~~~
/tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandvideo.h:97:48: warning: 'struct wl_surface' declared inside parameter list will not be visible outside of this definition or declaration
   97 | extern SDL_bool SDL_WAYLAND_own_surface(struct wl_surface *surface);
      |                                                ^~~~~~~~~~
/tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandvideo.c:134:6: error: conflicting types for 'SDL_WAYLAND_register_surface'
  134 | void SDL_WAYLAND_register_surface(struct wl_surface *surface)
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandvideo.c:31:
/tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandvideo.h:95:13: note: previous declaration of 'SDL_WAYLAND_register_surface' was here
   95 | extern void SDL_WAYLAND_register_surface(struct wl_surface *surface);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandvideo.c:148:10: error: conflicting types for 'SDL_WAYLAND_own_surface'
  148 | SDL_bool SDL_WAYLAND_own_surface(struct wl_surface *surface)
      |          ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandvideo.c:31:
/tmp/repository/vendor/SDL-upstream/src/video/wayland/SDL_waylandvideo.h:97:17: note: previous declaration of 'SDL_WAYLAND_own_surface' was here
   97 | extern SDL_bool SDL_WAYLAND_own_surface(struct wl_surface *surface);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~
make[3]: *** [Makefile:694: build/SDL_waylandvideo.lo] Error 1
```
Note: I am trying to build on an **Ubuntu 20.04** for **ARM64/glibc** (*not x64!!*) in case that is related. I'm not running a cross-compiler though, I ran it on ARM64 Ubuntu.

**Comment by flibitijibibo** [comment]
I want to say that it's this bit here...

https://github.com/libsdl-org/SDL/blob/main/src/video/wayland/SDL_waylanddyn.h#L150-L156

I think we need some Wayland includes here. Maybe `#include <wayland-client.h>`? Basically what you're running into is a situation where, because dynamic mode is turned off, it's not getting the full type information for wl_surface by the time you get to the bottom of SDL_waylandvideo.h. We have the information for dynamic mode so it's almost certainly an include needed in this block specifically (there's a lot of indirection so not easy to tell, but SDL_waylanddyn.h is getting included as part of SDL_sysvideo.h).

**Comment by ell1e** [comment]
Yes, I'm still using `--disable-shared` since I usually ship SDL2 baked into the binary. So it seems that is a bit undertested? Maybe a CI path for that cold help

**Comment by flibitijibibo** [comment]
Figured out what it actually is: Disabling Vulkan causes this issue. The Vulkan headers include wayland-client.h, so we just need to add a new include to take that into account.

Patch incoming...

**Comment by flibitijibibo** [comment]
Tested locally and #4585 fixes it for me, as long as it works for you too and CI likes it this should be good to go.

**Comment by ell1e** [comment]
I'm running the build right now on https://github.com/libsdl-org/SDL/pull/4585/commits/ddde8e1a1202edaed973531c4b88eeed0f2e91f8 - this machine is kind of slow though, so it might be 10-15 minutes before I can report back. Very excited you looked into this so quickly :+1:

**Comment by ell1e** [comment]
Yup, it worked! But I didn't test your 2nd commit yet

**Comment by flibitijibibo** [comment]
The second commit is thankfully a lot safer; basically any C file that included video.h first doesn't need to include dyn.h as well, since the -E output is identical regardless of configuration.

Thanks for checking this out!
