### ISSUE TITLE
SDL 2.0.14 RC macOS framework is missing SDL_misc.h

### ISSUE THREAD

**Issue by SDLBugzilla** [libsdl-org/SDL#3918]
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** 2.0.14
**Reported for operating system, platform:** Mac OS X (All), All

# Comments on the original bug report:

On 2020-12-11 01:45:09 +0000, Cameron Gutman wrote:

> Attempting to #include <SDL.h> causes a compilation error because SDL_misc.h is not included in SDL2.framework in the 2.0.14 RC DMG.
> 
> SDL2.framework/Versions/A/Headers/SDL.h:63:10: fatal error: 'SDL_misc.h' file not found
> #include "SDL_misc.h"
>          ^~~~~~~~~~~~
> 1 error generated.

On 2020-12-13 08:23:27 +0000, Sam Lantinga wrote:

> Fixed, thanks!
