### ISSUE TITLE
SDL2 stopped to work starting from 2.0.16 release

### ISSUE THREAD

**Issue by Zenitur** [libsdl-org/SDL#14782]
Hi all. SDL2 stopped to work on my OS starting from 2.0.16 release. It shows black screen when I trying to start any application.

Hardware configuration:

- AMD Phenom X6 1045T
- 16 Gb RAM DDR3
- AMD Radeon R9 290X

Software configuration:

- Debian 7.0 (with the latest updates, including LTS updates from Freexian)
- Both 32-bit and 64-bit architectures
- Linux 4.15.18 (from esm-infra LTS repository)
- Videodriver: libdrm 2.4.97, Mesa 19.0, xf86-video-amdgpu 18.1
- X-Server 1.15
- libX11 1.6.2
- libvulkan 1.1.73
- Amdvlk 18.40

I tried to run Steam, OpenXray, Vangers and some more apps.
There is no problem with Debian 8 and newer.  Please help to debug and fix the problem in my previous Debian 7 distro that I still using sometimes. I attach the video with an error.
[Video [MP4]](https://0x0.st/PHzY.mp4)

**Comment by smcv** [comment]
> Debian 7.0

This is an operating system from 2013. I would recommend upgrading. The current Debian release is Debian 13, released in mid 2025.

Or, if you're particularly attached to Debian 7 because you want to keep your operating system unchanging, I suggest using Debian 7's packaged SDL so that that, too, does not change.

> I tried to run Steam

Running Steam on Debian [officially requires Debian 11 or later since August 2025](https://help.steampowered.com/en/faqs/view/107F-BB20-FB5A-1CE4) (the support article doesn't specifically state a version of any particular OS, but Debian 11 is the oldest that has glibc ≥ 2.31). Running Steam on older Debian releases may stop working at any time.

**Comment by icculus** [comment]
Yeah, for something this old, the most useful action would be for _you_ to bisect SDL on your machine and see what commit specifically broke it, between the "release-2.0.14" and "release-2.0.16" tags. It might be something we can work around if we know what caused the issue.

**Comment by Zenitur** [comment]
> the most useful action would be for you to bisect SDL on your machine

Okay, I'll write when I find that commit.

**Comment by Zenitur** [comment]
https://github.com/libsdl-org/SDL/commit/531d83bf6a140fcb5a858c9f23c76198016db869
https://github.com/libsdl-org/SDL/commit/62a562dea20728726a497b4af49d591a2fa385de

First commit broke my build:
```
build/.libs/SDL_x11xinput2.o: In function `X11_Xinput2GrabTouch':
SDL_x11xinput2.c:(.text+0x8a5): undefined reference to `XIGrabTouchBegin'
build/.libs/SDL_x11xinput2.o: In function `X11_Xinput2UngrabTouch':
SDL_x11xinput2.c:(.text+0x8ef): undefined reference to `XIUngrabTouchBegin'
```

Second commit successfully builds, but SDL stopped to work.

<img width="1234" height="404" alt="Image" src="https://github.com/user-attachments/assets/9f19e4e4-00fa-477a-8089-6d9183242643" />

**Comment by icculus** [comment]
If you build the latest SDL2 release with `configure --enable-video-x11-xinput`, does it otherwise work?

**Comment by Zenitur** [comment]
No, it doesn't work with that parameter.
Also, I read https://github.com/libsdl-org/SDL/issues/4938 and I see that SDL stopped to work with libXi < 1.7.4. I have 1.7.2. I tried to upgrade libXi to 1.7.4 and now SDL works.
Is any solution to make it work with an older libXi? Or maybe increase requirements?

**Comment by icculus** [comment]
Ugh, sorry, I pasted `--enable` and forgot to change it to `--disable`. This _should_ fix the hang by removing the problem code.

Most people don't need multitouch, and the solution is probably to fix the configure script to let you build with the rest of XInput but not that one piece.

**Comment by Zenitur** [comment]
I think, configure script needs to check libXi >= 1.7.4 when video-x11-xinput is enabled.

The problem is also may appear with a bundled libSDL in a game from GOG or Steam.
